name: KiCad PR CI

on:
  pull_request:

jobs:
  kicad:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 #v6.0.2

      - name: Generate schematic PDF
        uses: actions-for-kicad/kicad-actions@v2-k10.0
        with:
          schematic_file_name: kicad/seven.kicad_sch
          symbol_libraries: "seven_lib=kicad/sym-lib/seven_lib.kicad_sym"
          schematic_output_pdf: true

      - name: Generate PCB artifacts
        uses: actions-for-kicad/kicad-actions@v2-k10.0
        with:
          pcb_file_name: kicad/seven.kicad_pcb
          footprint_libraries: "seven-lib=kicad/fp-lib/seven-fp.pretty"
          pcb_output_image: true

      - name: Run ERC and DRC
        id: validation
        continue-on-error: true
        uses: actions-for-kicad/kicad-actions@v2-k10.0
        with:
          schematic_file_name: kicad/seven.kicad_sch
          symbol_libraries: "seven_lib=kicad/sym-lib/seven_lib.kicad_sym"
          run_erc: true
          pcb_file_name: kicad/seven.kicad_pcb
          footprint_libraries: "seven-lib=kicad/fp-lib/seven-fp.pretty"
          run_drc: true

      - name: Upload schematic
        if: always()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f #v7.0.0
        with:
          name: Schematic
          path: ./schematic.pdf
          archive: false
          if-no-files-found: warn

      - name: Upload PCB image
        if: always()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f #v7.0.0
        with:
          name: PCB-Image
          path: ./pcb.png
          archive: false
          if-no-files-found: warn

      - name: Upload ERC and DRC reports
        if: always()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f #v7.0.0
        with:
          name: KiCad-Reports
          path: |
            ./erc.rpt
            ./drc.rpt
          if-no-files-found: warn

      - name: Fail job if ERC or DRC failed
        if: steps.validation.outcome == 'failure'
        run: exit 1
